In [1]:
import pandas as pd
import os 
import glob
import numpy as np

In [2]:
excel_file = '../../excel_rotor/F_total.xlsx'
df = pd.read_excel(excel_file)

In [3]:
fx_by_angle = []
fy_by_angle = []
mz_by_angle = []

cx_by_angle = []
cy_by_angle = []
cz_by_angle = []

angle = []
draft = []
vels = [6, 10, 12]
rot = []
vw = []
for i in range(12):
    for j in range(12): angle.append(i*30)
    for j in range(6): draft.append(8.5)
    for j in range(6): draft.append(16)
    for veloc in vels: vw.append(veloc)
    for veloc in vels: vw.append(veloc)
    for veloc in vels: vw.append(veloc)
    for veloc in vels: vw.append(veloc)
    for j in range(3): rot.append(100)
    for j in range(3): rot.append(180)
    for j in range(3): rot.append(100)
    for j in range(3): rot.append(180)
    
    
    fx_by_angle.append(df.iloc[i+3, 21])
    fx_by_angle.append(df.iloc[i+3, 26])
    fx_by_angle.append(df.iloc[i+3, 31])
    fx_by_angle.append(df.iloc[i+22, 21])
    fx_by_angle.append(df.iloc[i+22, 26])
    fx_by_angle.append(df.iloc[i+22, 31])
    fx_by_angle.append(df.iloc[i+3, 5])
    fx_by_angle.append(df.iloc[i+3, 10])
    fx_by_angle.append(df.iloc[i+3, 15])
    fx_by_angle.append(df.iloc[i+22, 5])
    fx_by_angle.append(df.iloc[i+22, 10])
    fx_by_angle.append(df.iloc[i+22, 15])

    fy_by_angle.append(df.iloc[i+3, 22])
    fy_by_angle.append(df.iloc[i+3, 27])
    fy_by_angle.append(df.iloc[i+3, 32])
    fy_by_angle.append(df.iloc[i+22, 22])
    fy_by_angle.append(df.iloc[i+22, 27])
    fy_by_angle.append(df.iloc[i+22, 32])
    fy_by_angle.append(df.iloc[i+3, 6])
    fy_by_angle.append(df.iloc[i+3, 11])
    fy_by_angle.append(df.iloc[i+3, 16])
    fy_by_angle.append(df.iloc[i+22, 6])
    fy_by_angle.append(df.iloc[i+22, 11])
    fy_by_angle.append(df.iloc[i+22, 16])

    mz_by_angle.append(df.iloc[i+3, 23])
    mz_by_angle.append(df.iloc[i+3, 28])
    mz_by_angle.append(df.iloc[i+3, 33])
    mz_by_angle.append(df.iloc[i+22, 23])
    mz_by_angle.append(df.iloc[i+22, 28])
    mz_by_angle.append(df.iloc[i+22, 33])
    mz_by_angle.append(df.iloc[i+3, 7])
    mz_by_angle.append(df.iloc[i+3, 12])
    mz_by_angle.append(df.iloc[i+3, 17])
    mz_by_angle.append(df.iloc[i+22, 7])
    mz_by_angle.append(df.iloc[i+22, 12])
    mz_by_angle.append(df.iloc[i+22, 17])

    cx_by_angle.append(df.iloc[i+41, 21])
    cx_by_angle.append(df.iloc[i+41, 26])
    cx_by_angle.append(df.iloc[i+41, 31])
    cx_by_angle.append(df.iloc[i+60, 21])
    cx_by_angle.append(df.iloc[i+60, 26])
    cx_by_angle.append(df.iloc[i+60, 31])
    cx_by_angle.append(df.iloc[i+41, 5])
    cx_by_angle.append(df.iloc[i+41, 10])
    cx_by_angle.append(df.iloc[i+41, 15])
    cx_by_angle.append(df.iloc[i+60, 5])
    cx_by_angle.append(df.iloc[i+60, 10])
    cx_by_angle.append(df.iloc[i+60, 15])

    cy_by_angle.append(df.iloc[i+41, 22])
    cy_by_angle.append(df.iloc[i+41, 27])
    cy_by_angle.append(df.iloc[i+41, 32])
    cy_by_angle.append(df.iloc[i+60, 22])
    cy_by_angle.append(df.iloc[i+60, 27])
    cy_by_angle.append(df.iloc[i+60, 32])
    cy_by_angle.append(df.iloc[i+41, 6])
    cy_by_angle.append(df.iloc[i+41, 11])
    cy_by_angle.append(df.iloc[i+41, 16])
    cy_by_angle.append(df.iloc[i+60, 6])
    cy_by_angle.append(df.iloc[i+60, 11])
    cy_by_angle.append(df.iloc[i+60, 16])

    cz_by_angle.append(df.iloc[i+41, 23])
    cz_by_angle.append(df.iloc[i+41, 28])
    cz_by_angle.append(df.iloc[i+41, 33])
    cz_by_angle.append(df.iloc[i+60, 23])
    cz_by_angle.append(df.iloc[i+60, 28])
    cz_by_angle.append(df.iloc[i+60, 33])
    cz_by_angle.append(df.iloc[i+41, 7])
    cz_by_angle.append(df.iloc[i+41, 12])
    cz_by_angle.append(df.iloc[i+41, 17])
    cz_by_angle.append(df.iloc[i+60, 7])
    cz_by_angle.append(df.iloc[i+60, 12])
    cz_by_angle.append(df.iloc[i+60, 17])

In [4]:
new_df = pd.DataFrame({
    'Angulo': angle,
    'Calado': draft,
    'Rotacao': rot,
    'Vw': vw,
    'fx': fx_by_angle,
    'fy': fy_by_angle,
    'mz': mz_by_angle,
    'cx': cx_by_angle,
    'cy': cy_by_angle,
    'cz': cz_by_angle,
    
})

In [5]:
new_df.head()

,Angulo,Calado,Rotacao,Vw,fx,fy,mz,cx,cy,cz
0,0,8.5,100,6,56.34,-92.27,-193668.16,1.798851,-0.776684,-0.006175
1,0,8.5,100,10,141.39,-252.74,926607.78,1.625172,-0.765879,0.010636
2,0,8.5,100,12,178.73,-338.74,817692.87,1.426644,-0.712837,0.006518
3,0,8.5,180,6,50.78,-91.79,-1016670.00,1.621328,-0.772643,-0.032416
4,0,8.5,180,10,152.57,-242.24,400871.00,1.753678,-0.734061,0.004601

In [6]:
new_df.to_csv('forces.csv')

In [7]:
df_old = pd.read_csv('../../abdias_suez/forces.csv')

In [8]:
df_old.head()
df_old['sum fx'] = (df_old['Fx_popa_bom'] + df_old['Fx_popa_bor'] + df_old['Fx_proa_bom'] + df_old['Fx_proa_bor'])/1000 # kN

In [9]:
idx = (new_df['fx'] - df_old['sum fx']).argmin()